### ISSUE TITLE
Add refer-a-friend content

### ISSUE THREAD

**Issue by connorff** [devsdogood/yss-mentor-resources#11]

**Comment by Niall-Sharma** [comment]
### Change made by me
Added the basic content in using Contenful but didn't try creating the form

### Requested layout for the form in case you haven't seen

```
Refer a friend to be a mentor!

Your Information
First Name		Last Name

Your Email

Your Friend’s Information
Your Friend’s Name		Your Friend’s Last Name

Your Friend’s Email
City
```

**Comment by connorff** [comment]
Looks great to me! Did Feleecia have any comments on the form inputs?

If you need any help creating forms, I'd be happy to help out.

**Comment by Niall-Sharma** [comment]
Feleecia shared with me a folder with all the content that would go on the pages. For the Refer a Friend page this layout + the other content I added using Contentful was all that was listed for the page. 

The big reason why I'm not working on creating the form myself is that I have no experience with React or TypeScript/JavaScript.

**Comment by connorff** [comment]
Gotcha, thanks for the info. I can add the form if that's fine by you.

**Comment by Niall-Sharma** [comment]
Sure! That's perfectly fine.

**Comment by connorff** [comment]
Just created PR #17 for adding the form. Let me know how it looks (you can check out the preview [here](https://yss-mentor-resources-496ymn69l-devsdogood.vercel.app/refer-a-friend)).

**Comment by Niall-Sharma** [comment]
Hi Connor, I checked out the form and it looks great but I was just wondering if you could add a quick tweak. Could you add a small bold header above the fields that deal with the user's information labeled "Your Information", and have another small bold header above the fields that deal with the friend labeled "Your Friends Information"?
Thanks!
### An abstract mock-up of the structure 
![image](https://user-images.githubusercontent.com/38828396/143364789-b1bafb9d-7098-433a-8efe-8fcd6295eec0.png)

**Comment by connorff** [comment]
Sorry for merging before getting your thoughts. How does this look?

![image](https://user-images.githubusercontent.com/40175891/143366496-dbb1f55e-0bf9-466a-a61c-520288273288.png)

**Comment by Niall-Sharma** [comment]
Great! Thank you for the help.

**Comment by connorff** [comment]
Awesome, I'll commit this to `master`. Thank you for volunteering your time and being super responsive!
